//go:build ignore

// Command gen-third-party-licenses walks the third-party module
// dependencies actually linked into ./cmd/meerkat (built with
// CGO_ENABLED=0, matching the release build in .goreleaser.yaml) and
// concatenates each module's license/notice text into a single
// THIRD-PARTY-LICENSES.txt.
//
// This satisfies the "reproduce the copyright notice" duty carried by
// our BSD-3-Clause and MIT dependencies when we redistribute compiled
// binaries, and propagates gopkg.in/yaml.v3's own NOTICE file.
//
// Deterministic and offline: it only shells out to `go list` against
// the module cache that `go mod download` already populated — no
// network access, no third-party tool required.
//
// Run via: go run gen-third-party-licenses.go
// Wired into .goreleaser.yaml's before.hooks.
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const outFile = "THIRD-PARTY-LICENSES.txt"

// mainModule is excluded: its own LICENSE/NOTICE ship separately via
// archives.files ("LICENSE*" and "NOTICE" in .goreleaser.yaml).
const mainModule = "github.com/zegit-zoo/meerkat"

// Candidate license/notice file names, checked in this order per
// module directory (module roots use varying conventions upstream).
var licenseNames = []string{
	"LICENSE", "LICENSE.txt", "LICENSE.md",
	"LICENCE", "LICENCE.txt",
	"COPYING", "COPYING.txt",
}

var noticeNames = []string{"NOTICE", "NOTICE.txt"}

type module struct {
	Path, Version, Dir string
}

func main() {
	mods, err := deps()
	if err != nil {
		fatal(err)
	}
	if len(mods) == 0 {
		fatal(fmt.Errorf("no third-party modules resolved — refusing to write an empty %s", outFile))
	}

	var buf bytes.Buffer
	buf.WriteString("Third-party licenses\n")
	buf.WriteString("=====================\n\n")
	buf.WriteString("meerkat statically links the Go modules listed below (built with\n")
	buf.WriteString("CGO_ENABLED=0, so cgo-only dependencies such as blevesearch/go-faiss\n")
	buf.WriteString("are present in go.mod but not linked into this binary and are not\n")
	buf.WriteString("listed here). This file reproduces their license and notice texts\n")
	buf.WriteString("as required by their respective licenses.\n\n")
	fmt.Fprintf(&buf, "Generated by gen-third-party-licenses.go for %s.\n\n", mainModule)

	var missing []string
	for _, m := range mods {
		lic := findFile(m.Dir, licenseNames)
		not := findFile(m.Dir, noticeNames)
		if lic == "" && not == "" {
			missing = append(missing, fmt.Sprintf("%s (%s)", m.Path, m.Dir))
			continue
		}

		buf.WriteString(strings.Repeat("=", 78) + "\n")
		fmt.Fprintf(&buf, "%s %s\n", m.Path, m.Version)
		buf.WriteString(strings.Repeat("=", 78) + "\n\n")
		if lic != "" {
			writeFile(&buf, lic)
		}
		if not != "" {
			buf.WriteString("\n--- NOTICE ---\n\n")
			writeFile(&buf, not)
		}
		buf.WriteString("\n")
	}

	if len(missing) > 0 {
		fatal(fmt.Errorf("no LICENSE/NOTICE file found for module(s): %s", strings.Join(missing, "; ")))
	}

	if err := os.WriteFile(outFile, buf.Bytes(), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("gen-third-party-licenses: wrote %s covering %d third-party modules\n", outFile, len(mods))
}

// deps returns the de-duplicated, sorted set of third-party modules
// reachable from ./cmd/meerkat under CGO_ENABLED=0 — the same build
// configuration goreleaser uses, so cgo-only modules that are present
// in go.mod but never actually compiled in (e.g. blevesearch/go-faiss)
// are correctly excluded.
func deps() ([]module, error) {
	cmd := exec.Command("go", "list", "-deps", "-f",
		`{{if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}`,
		"./cmd/meerkat")
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -deps ./cmd/meerkat: %w\n%s", err, stderr.String())
	}

	seen := map[string]module{}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "|", 3)
		if len(parts) != 3 {
			continue
		}
		path := parts[0]
		if path == mainModule {
			continue
		}
		if _, ok := seen[path]; ok {
			continue
		}
		seen[path] = module{Path: path, Version: parts[1], Dir: parts[2]}
	}

	mods := make([]module, 0, len(seen))
	for _, m := range seen {
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })
	return mods, nil
}

func findFile(dir string, names []string) string {
	for _, n := range names {
		p := filepath.Join(dir, n)
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() {
			return p
		}
	}
	return ""
}

func writeFile(buf *bytes.Buffer, path string) {
	b, err := os.ReadFile(path)
	if err != nil {
		fatal(err)
	}
	buf.Write(b)
	if len(b) > 0 && b[len(b)-1] != '\n' {
		buf.WriteString("\n")
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-third-party-licenses:", err)
	os.Exit(1)
}
